export enum BaseDtoType {
    CaptureFrame = 0,
    ScreenData = 1,
    ScreenSize = 2,
    MachineName = 3,
    ClipboardText = 4,
    AudioSample = 5,
    CursorChange = 6,
    SelectScreen = 7,
    MouseMove = 8,
    MouseDown = 9,
    MouseUp = 10,
    Tap = 11,
    MouseWheel = 12,
    KeyDown = 13,
    KeyUp = 14,
    CtrlAltDel = 15,
    ToggleAudio = 17,
    ToggleBlockInput = 18,
    ClipboardTransfer = 19,
    KeyPress = 20,
    File = 22,
    WindowsSessions = 23,
    SetKeyStatesUp = 24,
    FrameReceived = 25,
    ToggleWebRtcVideo = 26,
    OpenFileTransferWindow = 27
}